// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, nitro (build-only using cloudflare as a default target),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

import { PRERENDER_ROUTES } from "./src/content/public-routes";

// Static export target: GitHub Pages. Every indexable route is an explicit
// registry-derived seed, so crawling cannot silently omit a new detail page.
export default defineConfig({
  tanstackStart: {
    prerender: {
      enabled: true,
      crawlLinks: false,
      failOnError: true,
    },
    pages: PRERENDER_ROUTES.map((path) => ({ path })),
    sitemap: {
      enabled: true,
      host: "https://vuzora.ru",
    },
  },
  vite: {
    environments: {
      client: {
        build: { outDir: "dist" },
      },
    },
  },
  // Static HTML is generated by TanStack Start's native prerenderer. Nitro's
  // Vite SSR bridge does not provide a renderer to its static preset in this
  // toolchain, so leaving it disabled avoids a server-only build path.
  nitro: false,
});
